version: '3.8'

services:
  app:
    build: .
    ports:
      - "3030:3030" 
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - postgres
    container_name: app_container

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ERP
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: